apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
spec:
  selector:
    matchLabels:
      app: testapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  template:
    metadata:
      labels:
        app: testapp
      annotations:
        fluentd.io/parser: logfmt
    spec:
      containers:
        - name: testapp
          image: islishude/testapp
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "256Mi"
              cpu: "256m"
          readinessProbe:
            tcpSocket:
              port: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: "/ping"
